name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        nim: [2.0.16, 2.2.6]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install Nim
      uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nim }}

    - name: Upgrade nimble
      run: nimble install -y nimble

    - name: Test
      run: nimble test -y
